server:
  port: 8084

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: course_service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: localhost
      port: 6384

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true

storage:
  base-dir: media/uploads
  file-types:
    video:
      sub-dir: videos
      max-file-size: 1000MB
      allowed-mime-types:
        - video/mp4
        - video/mpeg
      allowed-extensions:
        - mp4
        - mpeg
    image:
      sub-dir: images
      max-file-size: 100MB
      allowed-mime-types:
        - image/jpeg
        - image/png
      allowed-extensions:
        - jpg
        - jpeg
        - png
    pdf:
      sub-dir: pdfs
      max-file-size: 20MB
      allowed-mime-types:
        - application/pdf
      allowed-extensions:
        - pdf

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: TRACE

kafka:
  bootstrap-servers: localhost:9092
  consumer-group-id: course-service-group
  session-timeout-ms: 10000
  max-partition-fetch-bytes: 1048576
  max-poll-records: 500
  max-poll-interval-ms: 300000
  mentor-action: mentor-action-topic
  producer:
    enable: true


user:
  service:
    url: http://localhost:8081

springdoc:
  api-docs:
    enabled: true

  swagger-ui:
    docExpansion: full
    defaultModelsExpandDepth: 1
    defaultModelExpandDepth: 3
    defaultModelRendering: schema
    operationsSorter: method
    tagsSorter: alpha

  model-converters:
    pageable-converter:
      enabled: true
