server:
  port: 8084

spring:
  application:
    name: course_service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: consort
    password: 2231251fsad1
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


  data:
    redis:
      host: localhost
      port: 6384


  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true

storage:
  base-dir: media/uploads
  file-types:
    video:
      sub-dir: videos
      max-file-size: 1000MB
      allowed-mime-types:
        - video/mp4
        - video/mpeg
      allowed-extensions:
        - mp4
        - mpeg
    image:
      sub-dir: images
      max-file-size: 50MB
      allowed-mime-types:
        - image/jpeg
        - image/png
      allowed-extensions:
        - jpg
        - jpeg
        - png
    pdf:
      sub-dir: pdfs
      max-file-size: 20MB
      allowed-mime-types:
        - application/pdf
      allowed-extensions:
        - pdf


logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: TRACE