server:
  port: 8084

spring:
  application:
    name: course_service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/consort_group
    username: consort
    password: 2231251fsad1
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


  data:
    redis:
      host: localhost
      port: 6384


  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB



video:
  storage:
    location: ./uploads/videos
    max-file-size: 1000MB


logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: TRACE